export const REQUEST_USERS_PENDING = 'REQUEST_USERS_PENDING';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';

export const REQUEST_TOPIC_PENDING = 'REQUEST_TOPIC_PENDING';
export const REQUEST_TOPIC_SUCCESS = 'REQUEST_TOPIC_SUCCESS';
export const REQUEST_TOPIC_FAILED = 'REQUEST_TOPIC_FAILED';
export const INITIAL_TOPIC = 'INITIAL_TOPIC';

export const RESOURCE_LOADED = 'RESOURCE_LOADED';