export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';

export const REQUEST_TOPIC_PENDING = 'REQUEST_TOPIC_PENDING';
export const REQUEST_TOPIC_SUCCESS = 'REQUEST_TOPIC_SUCCESS';
export const REQUEST_TOPIC_FAILED = 'REQUEST_TOPIC_FAILED';